### ISSUE TITLE
`npm i` in instructions

### ISSUE THREAD

**Issue by glrta** [oliverjam/learn-node-error-handling#1]
Could `npm i` be included as step 2 in the installation instructions? They skipped this step as it wasn't listed.

**Comment by oliverjam** [comment]
Yeah I pushed a fix based on the Slack convo before I saw this 😅 

I do wonder at what point in the course we could remove the "clone and install" instructions. Maybe it's worth always being clear about this

Fixed in https://github.com/oliverjam/learn-node-error-handling/commit/d5ed91faa5bc01f07bf0cb9fb018a843c3aaae9c
